language: python
python:
- 3.5
- 3.6
- 3.7
install:
- pip install -r requirements.txt
- python setup.py install
deploy:
  provider: pypi
  user: __token__
  password:
    secure: bzfu3u+dyrGC1H9Rwg6TCxZg4VeedqgUS/gKYqKMLllBEbAHTLn3vNE21nu8M4KTTKcVdFfVSHUwixB2c9+e4bDs9OtXNenb2xWz6DfYBFQLCcMjpl1xHF9NUS5W6Jb+Vy8m/642C8GDf0OxDtf/doKPmvqZlzK92hzNy0CAneoGApOzWhOsCzOzKsMl/iR28VJgf5CgBeceHDyY/C9bQJdWS0FoD3oFZevt+gH8cxQ4TKjOKEROnA9pogx4hP/ByWZ8trOhDHQaG1wORrKG11xP/pxTMdELemfbeg/CNgSpC1k5XqnwyZ5mIMF3riW40OuVsX/C65LrW/jF0eHfRd2iRSe4iSDBc6I6shPdkw5ISlL0ghTuVOVFJJAtFT1jgvpUyarPIBn9OY0TUGV1rfA6B75asRhdut9ROzObSq8fVINgJZRwst3/cdGtLfoyBoIGq3ZFODz79ghdGbnkBvXzOs3Z6ixxbfufi9vrdjK6Oo0LrMTV0/3efEAnjb1QWFW3uj2x+sw0ZfOv5Dnh690g1qjPiUSDjZLYf4kTnKodt12dNe9POrSFJJs3Dkj0y9bJPO5OIdMvk3ahFsVZ9z87Z6x8SRr9zuK+ILiTu3O8pN46OL6MIz4XvbcGacuMr2wPbGTR4hiNIgOlhb8qyUdlut6ghwr1nQIDhgwXtVc=
  distributions: sdist bdist_wheel bdist_egg
  skip_existing: true
  on:
    branch: develop
  server: https://test.pypi.org/legacy/
script:
- echo "Done"
